In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import scipy.stats as stats

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import r2_score
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Lasso
from sklearn.datasets import make_classification

In [37]:
from google.colab import files
uploaded = files.upload()

Saving heart.csv to heart (1).csv


In [38]:
df= pd.read_csv('heart.csv')
df.head()


age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0   63    1                3         145          233                    1   
1   37    1                2         130          250                    0   
2   41    0                1         130          204                    0   
3   56    1                1         120          236                    0   
4   57    0                0         120          354                    0   

   restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0        0     150      0      2.3      0                  0     1       1  
1        1     187      0      3.5      0                  0     2       1  
2        0     172      0      1.4      2                  0     2       1  
3        1     178      0      0.8      2                  0     2       1  
4        1     163      1      0.6      2                  0     2       1

In [39]:
df.head()

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0   63    1                3         145          233                    1   
1   37    1                2         130          250                    0   
2   41    0                1         130          204                    0   
3   56    1                1         120          236                    0   
4   57    0                0         120          354                    0   

   restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0        0     150      0      2.3      0                  0     1       1  
1        1     187      0      3.5      0                  0     2       1  
2        0     172      0      1.4      2                  0     2       1  
3        1     178      0      0.8      2                  0     2       1  
4        1     163      1      0.6      2                  0     2       1

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [43]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

### **CALLING AND FITTING OF AL ALGORITHMS**

In [44]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [45]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

### **CALCULATING ACCURACY**

In [46]:
y_pred=clf1.predict(x_test)
y_pred1=clf2.predict(x_test)

In [47]:
print("accuracy for LR",accuracy_score(y_test,y_pred))
print("accuracy for DT",accuracy_score(y_test,y_pred1))

accuracy for LR 0.9016393442622951
accuracy for DT 0.8524590163934426


In [48]:
print(classification_report(y_test,y_pred))  # logistic regression

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61



In [49]:
print(classification_report(y_test,y_pred1))  # decicsion tree

              precision    recall  f1-score   support

           0       0.93      0.78      0.85        32
           1       0.79      0.93      0.86        29

    accuracy                           0.85        61
   macro avg       0.86      0.86      0.85        61
weighted avg       0.86      0.85      0.85        61



In [50]:
confusion_matrix(y_test,y_pred)

array([[26,  6],
       [ 0, 29]])

In [51]:
confusion_matrix(y_test,y_pred1)

array([[25,  7],
       [ 2, 27]])

### **PRECESION_SCORE,RECALL AND F1_SCORE IN LOGISTIC REGRESSION AND DECISION TREE**

In [53]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [54]:
print("For logistic regression model")
print("-"*50)
cdf=pd.DataFrame(confusion_matrix(y_test,y_pred),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("precision-",precision_score(y_test,y_pred))
print("recall-",recall_score(y_test,y_pred))
print("f1 score-",f1_score(y_test,y_pred))

For logistic regression model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
precision- 0.8285714285714286
recall- 1.0
f1 score- 0.90625


In [55]:
print("For dicision tree model")
print("-"*50)
cdf=pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("precision-",precision_score(y_test,y_pred1))
print("recall-",recall_score(y_test,y_pred1))
print("f1 score-",f1_score(y_test,y_pred1))

For dicision tree model
--------------------------------------------------
    0   1
0  25   7
1   2  27
--------------------------------------------------
precision- 0.7941176470588235
recall- 0.9310344827586207
f1 score- 0.8571428571428571


In [56]:
precision_score(y_test,y_pred,average=None)

array([1.        , 0.82857143])